//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 10:32:31 PM CEST 
//


package sunset.gui.api.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="typeList" type="{ffapl/api}typeList" minOccurs="0"/>
 *         &lt;element name="procedureList" type="{ffapl/api}procedureList" minOccurs="0"/>
 *         &lt;element name="functionList" type="{ffapl/api}functionList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "typeList",
    "procedureList",
    "functionList"
})
@XmlRootElement(name = "apiSpecification")
public class ApiSpecification {

    protected TypeList typeList;
    protected ProcedureList procedureList;
    protected FunctionList functionList;

    /**
     * Gets the value of the typeList property.
     * 
     * @return
     *     possible object is
     *     {@link TypeList }
     *     
     */
    public TypeList getTypeList() {
        return typeList;
    }

    /**
     * Sets the value of the typeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeList }
     *     
     */
    public void setTypeList(TypeList value) {
        this.typeList = value;
    }

    /**
     * Gets the value of the procedureList property.
     * 
     * @return
     *     possible object is
     *     {@link ProcedureList }
     *     
     */
    public ProcedureList getProcedureList() {
        return procedureList;
    }

    /**
     * Sets the value of the procedureList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcedureList }
     *     
     */
    public void setProcedureList(ProcedureList value) {
        this.procedureList = value;
    }

    /**
     * Gets the value of the functionList property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionList }
     *     
     */
    public FunctionList getFunctionList() {
        return functionList;
    }

    /**
     * Sets the value of the functionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionList }
     *     
     */
    public void setFunctionList(FunctionList value) {
        this.functionList = value;
    }

}
