//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 10:32:31 PM CEST 
//


package sunset.gui.api.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sunset.gui.api.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sunset.gui.api.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SampleCode }
     * 
     */
    public SampleCode createSampleCode() {
        return new SampleCode();
    }

    /**
     * Create an instance of {@link ProcedureList }
     * 
     */
    public ProcedureList createProcedureList() {
        return new ProcedureList();
    }

    /**
     * Create an instance of {@link FunctionList }
     * 
     */
    public FunctionList createFunctionList() {
        return new FunctionList();
    }

    /**
     * Create an instance of {@link ApiSpecification }
     * 
     */
    public ApiSpecification createApiSpecification() {
        return new ApiSpecification();
    }

    /**
     * Create an instance of {@link TypeList }
     * 
     */
    public TypeList createTypeList() {
        return new TypeList();
    }

    /**
     * Create an instance of {@link SnippetCode }
     * 
     */
    public SnippetCode createSnippetCode() {
        return new SnippetCode();
    }

    /**
     * Create an instance of {@link SnippetList }
     * 
     */
    public SnippetList createSnippetList() {
        return new SnippetList();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link ParameterList }
     * 
     */
    public ParameterList createParameterList() {
        return new ParameterList();
    }

    /**
     * Create an instance of {@link Snippet }
     * 
     */
    public Snippet createSnippet() {
        return new Snippet();
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createType() {
        return new Type();
    }

    /**
     * Create an instance of {@link ApiEntry }
     * 
     */
    public ApiEntry createApiEntry() {
        return new ApiEntry();
    }

    /**
     * Create an instance of {@link Procedure }
     * 
     */
    public Procedure createProcedure() {
        return new Procedure();
    }

    /**
     * Create an instance of {@link Function }
     * 
     */
    public Function createFunction() {
        return new Function();
    }

}
