//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 10:32:31 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "ffapl/api", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sunset.gui.api.jaxb;
