//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 10:32:31 PM CEST 
//


package sunset.gui.api.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="snippetList" type="{ffapl/api}snippetList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "snippetList"
})
@XmlRootElement(name = "snippetCode")
public class SnippetCode {

    protected SnippetList snippetList;

    /**
     * Gets the value of the snippetList property.
     * 
     * @return
     *     possible object is
     *     {@link SnippetList }
     *     
     */
    public SnippetList getSnippetList() {
        return snippetList;
    }

    /**
     * Sets the value of the snippetList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SnippetList }
     *     
     */
    public void setSnippetList(SnippetList value) {
        this.snippetList = value;
    }

}
